version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "testtest"
      POSTGRES_PORT: 5432
    ports:
      - "5432"

  main_app:
      build: main_app
      environment:
        DB_URL: 'postgresql+asyncpg://test_user:testtest@database:5432/test'
        DEBUG: 0
        POSTGRES_PORT: 5432
        POSTGRES_HOST: 'database'
      ports:
        - "8001:8001"
      links:
        - "postgres:database"
      depends_on:
        - postgres


  nomain_app:
    build: nomain_app
    environment:
      - DEBUG=0
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    links:
      - "main_app:main_app"
